// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksedjgnbptnovrhfuzif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzZWRqZ25icHRub3ZyaGZ1emlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1ODE4NzgsImV4cCI6MjA1NjE1Nzg3OH0.1Tz2k-oPDeLcbLM3G34q7EhYlmG4Zd1z8OiLwPmF2SY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);